spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/diemthuong
    username: root
    password: admin12345
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
