spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/diemthuong
spring.datasource.username=root
spring.datasource.password=admin12345
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false
server.servlet.session.timeout=60m
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE